-- =============================================================================
-- GoldPOS — Phase 4: locations (baki), inventory (one row = one physical piece),
-- inventory movements, barcode.
--
-- Rules
--   * Clients can only SELECT inventory/movements. Every stock change goes through
--     a SECURITY DEFINER RPC that checks tenant + permission + store access, locks
--     the affected rows (FOR UPDATE) and ALWAYS writes a movement + audit log.
--   * A piece carries its own purity/weights/pricing components (copied from the
--     product on receipt, editable) because buyback pieces may have no product.
--   * Barcode: GOLD-000001, unique per tenant, generated by gold_next_sequence.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- gold_locations — baki / slot / gudang / etalase inside a store
-- -----------------------------------------------------------------------------
create table public.gold_locations (
  id         uuid primary key default gen_random_uuid(),
  tenant_id  uuid not null default public.gold_current_tenant_id()
             references public.gold_tenants (id) on delete cascade,
  store_id   uuid not null,
  parent_id  uuid,
  code       text not null check (code ~ '^[A-Z0-9-]{1,20}$'),
  name       text not null check (length(trim(name)) between 1 and 80),
  type       text not null default 'BAKI' check (type in ('BAKI', 'SLOT', 'ETALASE', 'GUDANG')),
  sort_order integer not null default 0,
  is_active  boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, code),
  unique (tenant_id, id),
  unique (tenant_id, store_id, id),
  foreign key (tenant_id, store_id) references public.gold_stores (tenant_id, id) on delete cascade,
  foreign key (tenant_id, store_id, parent_id) references public.gold_locations (tenant_id, store_id, id) on delete restrict,
  check (parent_id is null or parent_id <> id)
);

create index gold_locations_tenant_store_idx on public.gold_locations (tenant_id, store_id, is_active, sort_order);
create index gold_locations_parent_idx on public.gold_locations (parent_id);

create trigger gold_locations_updated_at before update on public.gold_locations
  for each row execute function public.gold_set_updated_at();
create trigger gold_locations_audit after insert or update or delete on public.gold_locations
  for each row execute function public.gold_audit_row('LOCATION');

alter table public.gold_locations enable row level security;
revoke all on public.gold_locations from anon, authenticated;
grant select, insert, update, delete on public.gold_locations to authenticated;

create policy gold_locations_select on public.gold_locations for select to authenticated
  using (tenant_id = public.gold_current_tenant_id() and public.gold_can_access_store(store_id));
create policy gold_locations_insert on public.gold_locations for insert to authenticated
  with check (tenant_id = public.gold_current_tenant_id() and public.gold_can_access_store(store_id)
              and public.gold_has_permission('inventory.manage'));
create policy gold_locations_update on public.gold_locations for update to authenticated
  using (tenant_id = public.gold_current_tenant_id() and public.gold_can_access_store(store_id)
         and public.gold_has_permission('inventory.manage'))
  with check (tenant_id = public.gold_current_tenant_id() and public.gold_can_access_store(store_id));
create policy gold_locations_delete on public.gold_locations for delete to authenticated
  using (tenant_id = public.gold_current_tenant_id() and public.gold_can_access_store(store_id)
         and public.gold_has_permission('inventory.manage'));

-- -----------------------------------------------------------------------------
-- gold_inventory — one row per physical piece
-- -----------------------------------------------------------------------------
create table public.gold_inventory (
  id            uuid primary key default gen_random_uuid(),
  tenant_id     uuid not null references public.gold_tenants (id) on delete cascade,
  store_id      uuid not null,
  location_id   uuid,
  product_id    uuid,
  category_id   uuid not null,
  purity_id     uuid not null,
  barcode       text not null check (barcode ~ '^[A-Z0-9-]{3,40}$'),
  serial_number text check (length(serial_number) <= 60),
  name          text not null check (length(trim(name)) between 2 and 150),
  gross_weight  numeric(10,3) not null check (gross_weight > 0),
  stone_weight  numeric(10,3) not null default 0 check (stone_weight >= 0),
  gold_weight   numeric(10,3) generated always as (gross_weight - stone_weight) stored,
  stone_type    text check (length(stone_type) <= 80),
  cost_price    numeric(15,2) not null default 0 check (cost_price >= 0),
  labor_cost    numeric(15,2) not null default 0 check (labor_cost >= 0),
  stone_price   numeric(15,2) not null default 0 check (stone_price >= 0),
  margin_amount numeric(15,2) not null default 0 check (margin_amount >= 0),
  status        text not null default 'AVAILABLE'
                check (status in ('AVAILABLE', 'SOLD', 'BUYBACK', 'RESERVED', 'REPAIR', 'MELTED', 'DAMAGED', 'LOST')),
  source        text not null check (source in ('OPENING', 'PURCHASE', 'BUYBACK', 'TRADE_IN', 'RETURN')),
  notes         text check (length(notes) <= 1000),
  received_at   timestamptz not null default now(),
  created_by    uuid references auth.users (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  check (stone_weight < gross_weight),
  unique (tenant_id, barcode),
  unique (tenant_id, id),
  foreign key (tenant_id, store_id) references public.gold_stores (tenant_id, id) on delete restrict,
  foreign key (tenant_id, store_id, location_id) references public.gold_locations (tenant_id, store_id, id) on delete restrict,
  foreign key (tenant_id, product_id) references public.gold_products (tenant_id, id) on delete restrict,
  foreign key (tenant_id, category_id) references public.gold_categories (tenant_id, id) on delete restrict,
  foreign key (tenant_id, purity_id) references public.gold_purities (tenant_id, id) on delete restrict
);

create index gold_inventory_tenant_store_status_idx on public.gold_inventory (tenant_id, store_id, status);
create index gold_inventory_location_idx on public.gold_inventory (location_id);
create index gold_inventory_product_idx on public.gold_inventory (tenant_id, product_id);
create index gold_inventory_purity_idx on public.gold_inventory (tenant_id, purity_id);
create index gold_inventory_category_idx on public.gold_inventory (tenant_id, category_id);
create index gold_inventory_serial_idx on public.gold_inventory (tenant_id, serial_number) where serial_number is not null;
create index gold_inventory_created_at_idx on public.gold_inventory (tenant_id, created_at desc);
create index gold_inventory_name_idx on public.gold_inventory (tenant_id, lower(name));

create trigger gold_inventory_updated_at before update on public.gold_inventory
  for each row execute function public.gold_set_updated_at();

-- -----------------------------------------------------------------------------
-- gold_inventory_movements — immutable audit trail of every stock change
-- -----------------------------------------------------------------------------
create table public.gold_inventory_movements (
  id               bigint generated always as identity primary key,
  tenant_id        uuid not null references public.gold_tenants (id) on delete cascade,
  inventory_id     uuid not null,
  movement_type    text not null check (movement_type in (
                     'PURCHASE', 'SALE', 'BUYBACK', 'TRADE_IN', 'TRANSFER', 'ADJUSTMENT',
                     'STOCK_OPNAME', 'REPAIR_OUT', 'REPAIR_IN', 'MELT', 'RETURN')),
  quantity         integer not null check (quantity between -1 and 1), -- +1 in, -1 out, 0 move/status
  weight           numeric(10,3) not null,                            -- gold weight involved
  before_weight    numeric(10,3),                                     -- piece gross weight before
  after_weight     numeric(10,3),                                     -- piece gross weight after
  from_store_id    uuid,
  to_store_id      uuid,
  from_location_id uuid,
  to_location_id   uuid,
  from_status      text,
  to_status        text,
  reference_type   text,
  reference_id     uuid,
  notes            text check (length(notes) <= 1000),
  created_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  foreign key (tenant_id, inventory_id) references public.gold_inventory (tenant_id, id) on delete restrict
);

create index gold_movements_tenant_created_idx on public.gold_inventory_movements (tenant_id, created_at desc);
create index gold_movements_inventory_idx on public.gold_inventory_movements (inventory_id, created_at desc);
create index gold_movements_type_idx on public.gold_inventory_movements (tenant_id, movement_type, created_at desc);
create index gold_movements_store_idx on public.gold_inventory_movements (tenant_id, to_store_id, created_at desc);
create index gold_movements_reference_idx on public.gold_inventory_movements (reference_type, reference_id);

-- -----------------------------------------------------------------------------
-- RLS: read-only for clients
--   inventory : own tenant + accessible store + (inventory.view or pos.use)
--   movements : own tenant + inventory.view
-- -----------------------------------------------------------------------------
alter table public.gold_inventory enable row level security;
alter table public.gold_inventory_movements enable row level security;
revoke all on public.gold_inventory, public.gold_inventory_movements from anon, authenticated;
grant select on public.gold_inventory, public.gold_inventory_movements to authenticated;

create policy gold_inventory_select on public.gold_inventory for select to authenticated
  using (
    tenant_id = public.gold_current_tenant_id()
    and public.gold_can_access_store(store_id)
    and (public.gold_has_permission('inventory.view') or public.gold_has_permission('pos.use'))
  );

create policy gold_movements_select on public.gold_inventory_movements for select to authenticated
  using (tenant_id = public.gold_current_tenant_id() and public.gold_has_permission('inventory.view'));

-- -----------------------------------------------------------------------------
-- Internal helpers (not callable by clients)
-- -----------------------------------------------------------------------------

-- Resolves the caller and checks permission (+ optional store access). Returns tenant id.
create or replace function public.gold_require(p_permission text, p_store_id uuid default null)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_current_tenant_id();
begin
  if v_tenant is null then
    raise exception 'UNAUTHENTICATED' using errcode = '42501';
  end if;
  if not public.gold_has_permission(p_permission) then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  if p_store_id is not null and not public.gold_can_access_store(p_store_id) then
    raise exception 'STORE_FORBIDDEN' using errcode = '42501';
  end if;
  return v_tenant;
end;
$$;

create or replace function public.gold_next_barcode(p_tenant_id uuid)
returns text
language sql
security definer
set search_path = public
as $$
  select 'GOLD-' || lpad(public.gold_next_sequence(p_tenant_id, 'barcode')::text, 6, '0')
$$;

create or replace function public.gold_log_movement(
  p_tenant_id uuid, p_inventory_id uuid, p_type text, p_quantity integer, p_weight numeric,
  p_before_weight numeric, p_after_weight numeric,
  p_from_store uuid, p_to_store uuid, p_from_location uuid, p_to_location uuid,
  p_from_status text, p_to_status text,
  p_reference_type text, p_reference_id uuid, p_notes text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.gold_inventory_movements (
    tenant_id, inventory_id, movement_type, quantity, weight, before_weight, after_weight,
    from_store_id, to_store_id, from_location_id, to_location_id, from_status, to_status,
    reference_type, reference_id, notes, created_by)
  values (
    p_tenant_id, p_inventory_id, p_type, p_quantity, p_weight, p_before_weight, p_after_weight,
    p_from_store, p_to_store, p_from_location, p_to_location, p_from_status, p_to_status,
    p_reference_type, p_reference_id, nullif(trim(p_notes), ''), auth.uid())
$$;

create or replace function public.gold_log_audit(p_tenant_id uuid, p_action text, p_entity_type text, p_entity_id text, p_old jsonb, p_new jsonb)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.gold_audit_logs (tenant_id, user_id, action, entity_type, entity_id, old_data, new_data)
  values (p_tenant_id, auth.uid(), p_action, p_entity_type, p_entity_id, p_old, p_new)
$$;

-- Validates that a location belongs to the store (and tenant) and is active.
create or replace function public.gold_check_location(p_tenant_id uuid, p_store_id uuid, p_location_id uuid)
returns void
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_location_id is null then return; end if;
  if not exists (
    select 1 from public.gold_locations
    where id = p_location_id and tenant_id = p_tenant_id and store_id = p_store_id and is_active
  ) then
    raise exception 'INVALID_LOCATION' using errcode = '22023';
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- Internal: create pieces (used by receive RPC now, purchase/buyback RPCs later).
-- p_items: [{ gross_weight, stone_weight?, serial_number?, cost_price?, name?,
--             category_id?, purity_id?, stone_type?, labor_cost?, stone_price?, margin_amount? }]
-- Values not given fall back to the product (when p_product_id is set).
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_create_pieces(
  p_tenant_id uuid, p_store_id uuid, p_location_id uuid, p_product_id uuid,
  p_items jsonb, p_status text, p_source text, p_movement_type text,
  p_reference_type text, p_reference_id uuid, p_notes text
)
returns setof uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product record;
  v_item jsonb;
  v_id uuid;
  v_gross numeric;
  v_stone numeric;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'NO_ITEMS' using errcode = '22023';
  end if;
  if jsonb_array_length(p_items) > 200 then
    raise exception 'TOO_MANY_ITEMS' using errcode = '22023';
  end if;

  perform public.gold_check_location(p_tenant_id, p_store_id, p_location_id);

  if p_product_id is not null then
    select * into v_product from public.gold_products where id = p_product_id and tenant_id = p_tenant_id;
    if not found then
      raise exception 'PRODUCT_NOT_FOUND' using errcode = '22023';
    end if;
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_gross := (v_item ->> 'gross_weight')::numeric;
    v_stone := coalesce((v_item ->> 'stone_weight')::numeric, v_product.stone_weight, 0);

    insert into public.gold_inventory (
      tenant_id, store_id, location_id, product_id, category_id, purity_id, barcode, serial_number,
      name, gross_weight, stone_weight, stone_type, cost_price, labor_cost, stone_price, margin_amount,
      status, source, notes, created_by)
    values (
      p_tenant_id, p_store_id, p_location_id, p_product_id,
      coalesce((v_item ->> 'category_id')::uuid, v_product.category_id),
      coalesce((v_item ->> 'purity_id')::uuid, v_product.purity_id),
      public.gold_next_barcode(p_tenant_id),
      nullif(trim(v_item ->> 'serial_number'), ''),
      coalesce(nullif(trim(v_item ->> 'name'), ''), v_product.name),
      v_gross, v_stone,
      coalesce(nullif(trim(v_item ->> 'stone_type'), ''), v_product.stone_type),
      coalesce((v_item ->> 'cost_price')::numeric, v_product.cost_price, 0),
      coalesce((v_item ->> 'labor_cost')::numeric, v_product.labor_cost, 0),
      coalesce((v_item ->> 'stone_price')::numeric, v_product.stone_price, 0),
      coalesce((v_item ->> 'margin_amount')::numeric, v_product.margin_amount, 0),
      p_status, p_source, nullif(trim(p_notes), ''), auth.uid())
    returning id into v_id;

    perform public.gold_log_movement(p_tenant_id, v_id, p_movement_type, 1, v_gross - v_stone, null, v_gross,
      null, p_store_id, null, p_location_id, null, p_status, p_reference_type, p_reference_id, p_notes);
    return next v_id;
  end loop;
end;
$$;

revoke all on function public.gold_require(text, uuid) from public, anon, authenticated;
revoke all on function public.gold_next_barcode(uuid) from public, anon, authenticated;
revoke all on function public.gold_log_movement(uuid, uuid, text, integer, numeric, numeric, numeric, uuid, uuid, uuid, uuid, text, text, text, uuid, text) from public, anon, authenticated;
revoke all on function public.gold_log_audit(uuid, text, text, text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.gold_check_location(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public.gold_inventory_create_pieces(uuid, uuid, uuid, uuid, jsonb, text, text, text, text, uuid, text) from public, anon, authenticated;

-- -----------------------------------------------------------------------------
-- RPC: receive stock (opening stock / manual stock-in). Movement: ADJUSTMENT.
-- Supplier purchases get their own RPC (Phase 8, movement PURCHASE).
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_receive(
  p_store_id uuid, p_location_id uuid, p_product_id uuid, p_items jsonb, p_notes text default null
)
returns table (inventory_id uuid, barcode text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_require('inventory.manage', p_store_id);
  v_ids uuid[];
begin
  if p_product_id is null then
    raise exception 'PRODUCT_REQUIRED' using errcode = '22023';
  end if;

  select array_agg(x) into v_ids
  from public.gold_inventory_create_pieces(v_tenant, p_store_id, p_location_id, p_product_id, p_items,
    'AVAILABLE', 'OPENING', 'ADJUSTMENT', 'STOCK_IN', null, coalesce(p_notes, 'Stok masuk')) x;

  perform public.gold_log_audit(v_tenant, 'STOCK_IN', 'inventory', null, null,
    jsonb_build_object('store_id', p_store_id, 'product_id', p_product_id, 'inventory_ids', to_jsonb(v_ids)));

  return query select i.id, i.barcode from public.gold_inventory i where i.id = any (v_ids) order by i.barcode;
end;
$$;

-- -----------------------------------------------------------------------------
-- RPC: transfer pieces to another store/location. Movement: TRANSFER.
-- Only AVAILABLE / BUYBACK / DAMAGED pieces can be moved.
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_transfer(
  p_inventory_ids uuid[], p_to_store_id uuid, p_to_location_id uuid, p_notes text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_require('stock_transfer.manage', p_to_store_id);
  v_item record;
  v_count integer := 0;
begin
  if p_inventory_ids is null or cardinality(p_inventory_ids) = 0 then
    raise exception 'NO_ITEMS' using errcode = '22023';
  end if;
  if cardinality(p_inventory_ids) > 500 then
    raise exception 'TOO_MANY_ITEMS' using errcode = '22023';
  end if;
  if not exists (select 1 from public.gold_stores where id = p_to_store_id and tenant_id = v_tenant and is_active) then
    raise exception 'INVALID_STORE' using errcode = '22023';
  end if;
  perform public.gold_check_location(v_tenant, p_to_store_id, p_to_location_id);

  for v_item in
    select * from public.gold_inventory
    where tenant_id = v_tenant and id = any (p_inventory_ids)
    order by id
    for update
  loop
    if not public.gold_can_access_store(v_item.store_id) then
      raise exception 'STORE_FORBIDDEN' using errcode = '42501';
    end if;
    if v_item.status not in ('AVAILABLE', 'BUYBACK', 'DAMAGED') then
      raise exception 'INVALID_STATUS:%', v_item.barcode using errcode = '22023';
    end if;
    if v_item.store_id = p_to_store_id and v_item.location_id is not distinct from p_to_location_id then
      continue;
    end if;

    update public.gold_inventory set store_id = p_to_store_id, location_id = p_to_location_id where id = v_item.id;

    perform public.gold_log_movement(v_tenant, v_item.id, 'TRANSFER', 0, v_item.gold_weight,
      v_item.gross_weight, v_item.gross_weight, v_item.store_id, p_to_store_id,
      v_item.location_id, p_to_location_id, v_item.status, v_item.status, null, null, p_notes);
    v_count := v_count + 1;
  end loop;

  if v_count = 0 and not exists (select 1 from public.gold_inventory where tenant_id = v_tenant and id = any (p_inventory_ids)) then
    raise exception 'NOT_FOUND' using errcode = '22023';
  end if;

  perform public.gold_log_audit(v_tenant, 'TRANSFER_STOCK', 'inventory', null, null,
    jsonb_build_object('inventory_ids', to_jsonb(p_inventory_ids), 'to_store_id', p_to_store_id,
                       'to_location_id', p_to_location_id, 'moved', v_count));
  return v_count;
end;
$$;

-- -----------------------------------------------------------------------------
-- RPC: change piece status (repair, melt, damaged, lost, buyback -> available ...)
-- Optional new gross weight (e.g. after repair / melting loss).
-- SOLD / RESERVED are set only by sales (Phase 5).
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_change_status(
  p_inventory_id uuid, p_to_status text, p_new_gross_weight numeric default null, p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_require('inventory.manage');
  v_item record;
  v_type text;
  v_new_gross numeric;
begin
  select * into v_item from public.gold_inventory where id = p_inventory_id and tenant_id = v_tenant for update;
  if not found then
    raise exception 'NOT_FOUND' using errcode = '22023';
  end if;
  if not public.gold_can_access_store(v_item.store_id) then
    raise exception 'STORE_FORBIDDEN' using errcode = '42501';
  end if;

  -- allowed transitions -> movement type
  v_type := case
    when v_item.status in ('AVAILABLE', 'BUYBACK', 'DAMAGED') and p_to_status = 'REPAIR' then 'REPAIR_OUT'
    when v_item.status = 'REPAIR' and p_to_status in ('AVAILABLE', 'DAMAGED') then 'REPAIR_IN'
    when v_item.status in ('AVAILABLE', 'BUYBACK', 'DAMAGED', 'REPAIR') and p_to_status = 'MELTED' then 'MELT'
    when v_item.status in ('AVAILABLE', 'BUYBACK') and p_to_status = 'DAMAGED' then 'ADJUSTMENT'
    when v_item.status in ('BUYBACK', 'DAMAGED') and p_to_status = 'AVAILABLE' then 'ADJUSTMENT'
    when v_item.status in ('AVAILABLE', 'BUYBACK', 'DAMAGED', 'REPAIR') and p_to_status = 'LOST' then 'ADJUSTMENT'
    when v_item.status = 'LOST' and p_to_status = 'AVAILABLE' then 'ADJUSTMENT'
    else null
  end;
  if v_type is null then
    raise exception 'INVALID_TRANSITION' using errcode = '22023';
  end if;
  if p_to_status in ('LOST', 'DAMAGED', 'MELTED') and coalesce(trim(p_notes), '') = '' then
    raise exception 'NOTES_REQUIRED' using errcode = '22023';
  end if;

  v_new_gross := coalesce(p_new_gross_weight, v_item.gross_weight);
  if v_new_gross <= v_item.stone_weight then
    raise exception 'INVALID_WEIGHT' using errcode = '22023';
  end if;

  update public.gold_inventory set status = p_to_status, gross_weight = v_new_gross where id = v_item.id;

  perform public.gold_log_movement(v_tenant, v_item.id, v_type,
    case when p_to_status in ('LOST', 'MELTED') then -1 when v_item.status = 'LOST' then 1 else 0 end,
    v_new_gross - v_item.stone_weight, v_item.gross_weight, v_new_gross,
    v_item.store_id, v_item.store_id, v_item.location_id, v_item.location_id,
    v_item.status, p_to_status, null, null, p_notes);

  perform public.gold_log_audit(v_tenant, 'ADJUSTMENT', 'inventory', v_item.id::text,
    jsonb_build_object('status', v_item.status, 'gross_weight', v_item.gross_weight),
    jsonb_build_object('status', p_to_status, 'gross_weight', v_new_gross, 'notes', p_notes));
end;
$$;

-- -----------------------------------------------------------------------------
-- RPC: edit non-stock details of a piece (name, serial, pricing components, notes)
-- No movement (stock unchanged) but audited.
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_update_details(
  p_inventory_id uuid, p_name text, p_serial_number text, p_stone_type text,
  p_cost_price numeric, p_labor_cost numeric, p_stone_price numeric, p_margin_amount numeric, p_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_require('inventory.manage');
  v_old record;
begin
  select * into v_old from public.gold_inventory where id = p_inventory_id and tenant_id = v_tenant for update;
  if not found then
    raise exception 'NOT_FOUND' using errcode = '22023';
  end if;
  if not public.gold_can_access_store(v_old.store_id) then
    raise exception 'STORE_FORBIDDEN' using errcode = '42501';
  end if;
  if v_old.status in ('SOLD', 'MELTED') then
    raise exception 'INVALID_STATUS' using errcode = '22023';
  end if;

  update public.gold_inventory set
    name = trim(p_name),
    serial_number = nullif(trim(p_serial_number), ''),
    stone_type = nullif(trim(p_stone_type), ''),
    cost_price = p_cost_price,
    labor_cost = p_labor_cost,
    stone_price = p_stone_price,
    margin_amount = p_margin_amount,
    notes = nullif(trim(p_notes), '')
  where id = p_inventory_id;

  perform public.gold_log_audit(v_tenant, 'UPDATE_INVENTORY', 'inventory', p_inventory_id::text,
    to_jsonb(v_old), (select to_jsonb(i) from public.gold_inventory i where i.id = p_inventory_id));
end;
$$;

-- Sell-price quote for a physical piece (uses the piece's own weight/purity/components).
create or replace function public.gold_quote_inventory(p_inventory_id uuid, p_discount numeric default 0)
returns table (inventory_id uuid, rate_id uuid, sell_rate numeric, gold_value numeric,
               subtotal numeric, discount numeric, total numeric)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_tenant uuid := public.gold_current_tenant_id();
  v_i record;
begin
  if v_tenant is null then
    raise exception 'UNAUTHENTICATED' using errcode = '42501';
  end if;
  if not (public.gold_has_permission('inventory.view') or public.gold_has_permission('pos.use')) then
    raise exception 'FORBIDDEN' using errcode = '42501';
  end if;
  select * into v_i from public.gold_inventory where id = p_inventory_id and tenant_id = v_tenant;
  if not found or not public.gold_can_access_store(v_i.store_id) then
    return;
  end if;
  return query
  select v_i.id, q.rate_id, q.sell_rate, q.gold_value, q.subtotal, q.discount, q.total
  from public.gold_price_quote(v_tenant, v_i.purity_id, v_i.gold_weight, v_i.labor_cost,
                               v_i.stone_price, v_i.margin_amount, p_discount) q;
end;
$$;

revoke all on function public.gold_inventory_receive(uuid, uuid, uuid, jsonb, text) from public, anon;
revoke all on function public.gold_inventory_transfer(uuid[], uuid, uuid, text) from public, anon;
revoke all on function public.gold_inventory_change_status(uuid, text, numeric, text) from public, anon;
revoke all on function public.gold_inventory_update_details(uuid, text, text, text, numeric, numeric, numeric, numeric, text) from public, anon;
revoke all on function public.gold_quote_inventory(uuid, numeric) from public, anon;
grant execute on function public.gold_inventory_receive(uuid, uuid, uuid, jsonb, text) to authenticated;
grant execute on function public.gold_inventory_transfer(uuid[], uuid, uuid, text) to authenticated;
grant execute on function public.gold_inventory_change_status(uuid, text, numeric, text) to authenticated;
grant execute on function public.gold_inventory_update_details(uuid, text, text, text, numeric, numeric, numeric, numeric, text) to authenticated;
grant execute on function public.gold_quote_inventory(uuid, numeric) to authenticated;

-- Current sell price per AVAILABLE piece (same formula as gold_price_quote, discount 0).
create view public.gold_v_inventory_prices
with (security_invoker = true) as
select
  i.id as inventory_id,
  i.tenant_id,
  r.sell_price as sell_rate,
  round(i.gold_weight * r.sell_price, 0) + i.labor_cost + i.stone_price + i.margin_amount as sell_price
from public.gold_inventory i
left join public.gold_v_current_gold_rates r on r.tenant_id = i.tenant_id and r.purity_id = i.purity_id;

revoke all on public.gold_v_inventory_prices from anon, authenticated;
grant select on public.gold_v_inventory_prices to authenticated;

-- -----------------------------------------------------------------------------
-- Inventory summary for the list filter (count + total gold weight).
-- SECURITY INVOKER: runs under the caller's RLS, so it only sums visible pieces.
-- -----------------------------------------------------------------------------
create or replace function public.gold_inventory_summary(
  p_store_id uuid default null, p_location_id uuid default null, p_status text default null,
  p_category_id uuid default null, p_purity_id uuid default null, p_q text default null
)
returns table (item_count bigint, gold_weight numeric)
language sql
stable
security invoker
set search_path = public
as $$
  select count(*), coalesce(sum(i.gold_weight), 0)
  from public.gold_inventory i
  where (p_store_id is null or i.store_id = p_store_id)
    and (p_location_id is null or i.location_id = p_location_id)
    and (p_status is null or i.status = p_status)
    and (p_category_id is null or i.category_id = p_category_id)
    and (p_purity_id is null or i.purity_id = p_purity_id)
    and (p_q is null or p_q = ''
         or i.barcode ilike '%' || p_q || '%' or i.name ilike '%' || p_q || '%' or i.serial_number ilike '%' || p_q || '%')
$$;

revoke all on function public.gold_inventory_summary(uuid, uuid, text, uuid, uuid, text) from public, anon;
grant execute on function public.gold_inventory_summary(uuid, uuid, text, uuid, uuid, text) to authenticated;
